### ISSUE TITLE
Please add an RSS feed

### ISSUE THREAD

**Issue by btbytes** [shreevatsa/site#1]
There are a few people (like me) who still like to use RSS as a way to catch up on blogs (twitter is too fast paced like a stream.. very hard to go back to the same place)... 

Since this is a Jekyll powered site, it should be easy to add RSS.

**Comment by shreevatsa** [comment]
Are you sure you want one? :-) There's a lot of junk on the site, incomplete drafts, posts being published out of date order, and (hopefully) edits to older posts. (But don't tell anyone, there's [this](https://shreevatsa.github.io/site/feed).)

**Comment by btbytes** [comment]
That works. Thanks ;)
