### ISSUE TITLE
tex-other: a couple of Go-based implementations

### ISSUE THREAD

**Issue by sbinet** [shreevatsa/site#12]
hi,

I believe you are the main curator of [github.com/tex-other](https://github.com/tex-other).
I may have 2 Go-based implementations to add to your curated list:

- [go-latex/latex](https://github.com/go-latex/latex) (basically a translation of `matplotlib`'s "mathtex" mode; not a complete TeX implementation)
- [star-tex (on SourceHut)](https://sr.ht/~sbinet/star-tex) (a complete TeX implementation, automatically transliterated from `.WEB` to `Go`)

_disclaimer:_ I am the main guilty party behind those attempts.

**Comment by shreevatsa** [comment]
Wow that's great, thank you so much! I'll take a look and add it to the list when I next get some time at the computer…

For the star-tex, the "web2go" sounds interesting too… is that also available somewhere?

**Comment by sbinet** [comment]
Sure, it's there:

- https://gitlab.com/cznic/web2go

**Comment by shreevatsa** [comment]
Sorry for the delay, and thank you so much once again! Really interesting and I hope to study them in detail soon; for now I've grabbed copies of all three of these into github.com/tex-other :-)

Really cool to see the automatically generated Go code, especially. Thanks for sharing!

**Comment by shreevatsa** [comment]
BTW I started a new discussion and mentioned your project at https://github.com/shreevatsa/webWEB/discussions/18 — some of the people there are interested in WEB and/or CWEB, so I'm sure they'll enjoy your work!
