### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by Charanleo25** [shreevatsa/site#17]
The Youtube playlist does not exist. 
The first link of "Audio / Video" section

**Comment by shreevatsa** [comment]
Thank you for reporting, could you say where this is? The URL of the page with the broken link?

**Comment by shreevatsa** [comment]
Ah I think it's about this page: https://shreevatsa.github.io/site/champu-ramayana.html — yes the youtube link seems broken now. Maybe the uploader took it private. Sad, can't rely on anything being up forever on YouTube. I'll edit the page if I find a working link / if I find someone has uploaded it somewhere else.

**Comment by shreevatsa** [comment]
Found a replacement playlist and fixed it: now says:

>  [By Shatavadhani Dr. R. Ganesh, in Kannada](https://www.youtube.com/playlist?list=PLoPhUooqLMHdXTsTEfMQGBWX4vKuokj98) (= [1](https://www.youtube.com/watch?v=veli-Qqo6FM) [2](https://www.youtube.com/watch?v=LUbeInTNa6Y) [3](https://www.youtube.com/watch?v=3HyuLMInnoc) [4](https://www.youtube.com/watch?v=T-4QDbW2MTE)) (audio only), about 6 hours total, going over good verses and passages from the entire text (after 40 minutes of introduction about Bhoja etc) and explaining them briefly.

etc.
